# Generated by Django 3.2 on 2021-10-26 09:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted', models.BooleanField(default=False, verbose_name="Promu en page d'accueil")),
                ('title', models.CharField(max_length=60, verbose_name='Titre')),
                ('extract', models.TextField(blank=True, null=True, verbose_name='Chapeau (H2)')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Corps')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name="Image de l'article")),
                ('file1', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Fichier #1 à télécharger')),
                ('file1_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nom du lien du Fichier #1')),
                ('file2', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Fichier #2 à télécharger')),
                ('file2_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nom du lien du Fichier #2')),
                ('meta_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='META title')),
                ('meta_description', models.CharField(blank=True, max_length=140, null=True, verbose_name='META description')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
