# Generated by Django 3.2 on 2021-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='contact@abeilles-aide-entraide.fr', max_length=50, verbose_name="Email d'expéditeur")),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mot de passe de la messagerie')),
                ('port', models.IntegerField(default=1025)),
            ],
            options={
                'verbose_name_plural': 'Email de contact',
            },
        ),
        migrations.CreateModel(
            name='NewsletterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendingblue_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clé API')),
                ('sendingblue_smtp_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clé SMTP')),
            ],
            options={
                'verbose_name_plural': 'Réglage Newsletter',
            },
        ),
        migrations.CreateModel(
            name='RecipientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email de réception')),
            ],
            options={
                'verbose_name_plural': 'Email de réception',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default='#', max_length=50, verbose_name='Page Facebook')),
                ('instagram', models.CharField(default='#', max_length=50, verbose_name='Page Instagram')),
                ('twitter', models.CharField(default='#', max_length=50, verbose_name='Page Twitter')),
                ('linkedin', models.CharField(default='#', max_length=50, verbose_name='Page Linkedin')),
            ],
            options={
                'verbose_name_plural': 'Réseaux sociaux',
            },
        ),
    ]
