# Generated by Django 3.2 on 2021-05-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Nombre total de paniers')),
                ('booked', models.IntegerField(blank=True, null=True, verbose_name='Nombre de paniers réservés')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Panier',
            },
        ),
    ]
